### ISSUE TITLE
Default batch_size for reverse

### ISSUE THREAD

**Issue by sirmarcel** [lycantropos/lz#29]
Hello! Great package. Thanks for the work!

I have a quick suggestion: I've noticed that using `reverse` on large files consumes irresponsible amounts of memory. I think the reason is [this](https://github.com/lycantropos/lz/blob/4c1a0a1eba16b47d518e3a104b8d8e33b6fe6ac0/lz/reversal.py#L157), which as far as I can tell makes `lz` default to the entire file size as chunk size for reading. I'd kindly suggest to maybe default to `min(1024, stream_size)` or something similar.

Feel free to ignore this if you prefer to push such decisions to users of the package -- just a suggestion!

**Comment by lycantropos** [comment]
I've changed default value to
https://github.com/lycantropos/lz/blob/632baaffc1c62cd644f6e67f0bcd7971ae6580da/lz/reversal.py#L102
starting from [0.11.1](https://pypi.org/project/lz/0.11.1), hope this helps

**Comment by sirmarcel** [comment]
Thanks! Seems reasonable. Closing this :)
